server: # 服务端口配置
  port: 9999
  servlet:
    context-path: /api
#  tomcat:
#    max-threads: 800

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    hikari:
      connection-timeout: 2000

  data:
    mongodb:
      database: test
      host: localhost
      port: 20001

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000


  thymeleaf:
    prefix: classpath:/templates/



#持久层 mybatis-springboot
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #mybatis-plus.typeEnumsPackage=com.baomidou.springboot.entity.enums
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      # 字段验证策略
      field-strategy: NOT_NULL
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
  type-aliases-package: com.ac.learn.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# pagehelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



